# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text=b'Fully qualified alias address of destination address.  May be non-local. Ex: john@example.org', max_length=256)),
                ('destination', models.EmailField(help_text=b'Fully qualified destination mailbox address.  May be non-local. Ex: jeff@example.com.', max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(help_text=b"Virtual mailbox domains, fully qualified.  Ex: 'example.org'.", max_length=256, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.SlugField(help_text=b"Virtual mail domain user address or LHS.  Ex: 'johnsmith'.", max_length=96)),
                ('salt', models.CharField(blank=True, help_text=b'Random password salt.', max_length=96)),
                ('shadigest', models.CharField(blank=True, help_text=b'Base64 encoding of SHA1 digest:Base64(sha1(password + salt) + salt).', max_length=256)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vmail.Domain')),
            ],
        ),
        migrations.AddField(
            model_name='alias',
            name='domain',
            field=models.ForeignKey(help_text=b'Domain owning the alias.', on_delete=django.db.models.deletion.CASCADE, to='vmail.Domain'),
        ),
        migrations.AlterUniqueTogether(
            name='mailuser',
            unique_together=set([('username', 'domain')]),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together=set([('source', 'destination')]),
        ),
    ]
